Fix vsce rewriting and refactor tests
Ericsson/CodecheckerVSCodePlugin pull request #128
Opened 2023-06-08 13:12 UTC by Discookie

The rewriter for publishing to the Marketplace also needs to rewrite a couple things within `yarn.lock`.

Updated the GH Actions files to use the new output syntax, and refactored tests - they now also test `vsce package` on the plugin.

2023-06-08 16:12 UTC, vodorok requested changes
Please see my remarks

2023-06-08 16:12 UTC, vodorok commented on .github/workflows/test.yml
>  # Triggers the workflow on push or pull request events.
Is this comment still apply?

2023-06-08 16:12 UTC, vodorok commented on .github/workflows/package.yml
> +# Triggers the workflow on push or pull request events.
Triggers on workflow calls also, instead of push or pull request.

2023-06-09 08:45 UTC, Discookie commented on .github/workflows/deploy.yml
> +    name: Version dummy
Indeed it is not, fixed.

2023-06-09 08:45 UTC, Discookie commented on .github/workflows/test.yml
>  # Triggers the workflow on push or pull request events.
Whoops, slight ctrl-C issue, fixed.

2023-06-09 09:22 UTC, vodorok approved these changes
LGTM

2023-06-09 11:33 UTC, merged