Add GitHub actions
Ericsson/CodecheckerVSCodePlugin pull request #4
Opened 2021-07-09 07:07 UTC by csordasmarton

> Closes #2

2021-07-09 07:09 UTC, csordasmarton commented
@Discookie I added the linter tests to the github actions so it will run tests on every pull requests. I also enabled some more rules (e.g.: to prevent long lines, use consistent style code, etc.). Please review it.

2021-07-09 12:27 UTC, Discookie requested changes
A larger correction, and a couple of suggestions.

Overall I'm not sure if using ESLint for stylistic linting is a good idea, a tool like [Prettier] is much better suited for the job.
Maybe expanding the linter's checks should be its own PR/issue, separate from this?

[Prettier]: https://prettier.io/

2021-07-12 06:38 UTC, csordasmarton commented on .github/workflows/test.yml
> +        run: npm install
Okay, good point, I changed it to yarn.

2021-07-12 06:41 UTC, csordasmarton commented on .eslintrc.json
> +        "max-len": ["error", { "code": 80 }],
I checked it and most of the users use 120 max length for TypeScript. So I changed it to 120 too.

By the way if it is not enough, we can save some extra space if we don't use 4 spaces for indentation but 2.

2021-07-12 06:41 UTC, csordasmarton commented on .eslintrc.json
> +        "indent": ["error", 4],
I changed all the reports to errors.

2021-07-12 06:43 UTC, csordasmarton commented
For now I think one tool is enough for us and I recommend to use ESLint. Later we can introduce Prettier if we still want.

2021-07-12 10:31 UTC, Discookie approved these changes
Sure thing, LGTM!

2021-07-12 10:51 UTC, merged